"""Build deterministic Rust notices from Cargo's locked, target-filtered graph.

Run after cargo fetch. Uses only local crate sources and reviewed upstream
fallback texts; no network or license inference occurs in this generator.
"""
import argparse
import gzip
import hashlib
import io
import json
from pathlib import Path
import re
import subprocess
import tarfile

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "app/assets/licenses"
TARGETS = ["x86_64-pc-windows-gnu", "aarch64-linux-android",
           "armv7-linux-androideabi", "aarch64-apple-ios"]


def sha(data):
    return hashlib.sha256(data).hexdigest()


def locked_packages():
    selected = {}
    for target in TARGETS:
        result = subprocess.run([
            "cargo", "metadata", "--format-version", "1", "--locked", "--offline",
            "--filter-platform", target, "--manifest-path",
            str(ROOT / "native/engine_shim/Cargo.toml"),
        ], check=True, capture_output=True, text=True, encoding="utf-8")
        metadata = json.loads(result.stdout)
        packages = {p["id"]: p for p in metadata["packages"]}
        nodes = {n["id"]: n for n in metadata["resolve"]["nodes"]}
        todo = [metadata["resolve"]["root"]]
        visited = set()
        while todo:
            package_id = todo.pop()
            if package_id in visited:
                continue
            visited.add(package_id)
            package = packages[package_id]
            if package["source"] is not None:
                selected[package_id] = package
            for dep in nodes[package_id]["deps"]:
                if any(kind["kind"] != "dev" for kind in dep["dep_kinds"]):
                    todo.append(dep["pkg"])
    return sorted(selected.values(), key=lambda p: (p["name"], p["version"]))


def license_files(package):
    directory = Path(package["manifest_path"]).parent
    files = [(str(p.relative_to(directory)), p) for p in sorted(directory.rglob("*"))
             if p.is_file() and re.match(r"^(licen[sc]e|copying|notice|copyright)([._-]|$)",
                                         p.name, re.IGNORECASE)]
    if not files and package["name"] == "nom-language":
        files = [("upstream/LICENSE", ROOT / "native/licenses/upstream/nom-LICENSE.txt")]
    if not files and package["name"] in {"tract-extra", "tract-transformers"}:
        files = [(f"upstream/{name}", ROOT / f"native/licenses/upstream/tract-{name}.txt")
                 for name in ["LICENSE", "LICENSE-MIT", "LICENSE-APACHE"]]
    if not files:
        raise RuntimeError(f"No reviewed license text: {package['name']} {package['version']}")
    return files


def source_archive(directory, name):
    """The complete unmodified published crate, in a reproducible source archive."""
    tar_bytes = io.BytesIO()
    with tarfile.open(fileobj=tar_bytes, mode="w") as archive:
        for path in sorted(directory.rglob("*")):
            if not path.is_file() or path.name == ".cargo-ok":
                continue
            data = path.read_bytes()
            info = tarfile.TarInfo(f"{name}/{path.relative_to(directory).as_posix()}")
            info.size = len(data)
            info.mode = 0o644
            archive.addfile(info, io.BytesIO(data))
    result = io.BytesIO()
    with gzip.GzipFile(fileobj=result, mode="wb", mtime=0) as compressed:
        compressed.write(tar_bytes.getvalue())
    return result.getvalue()


def generate():
    packages = locked_packages()
    groups = {}
    inventory = []
    outputs = {}
    for package in packages:
        component = f"{package['name']} {package['version']}"
        files = license_files(package)
        hashes = []
        for label, path in files:
            text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
            digest = sha(text.encode())
            hashes.append(digest)
            group = groups.setdefault(digest, {"text": text, "components": []})
            group["components"].append(f"{component} — {label}")
        entry = {"name": package["name"], "version": package["version"],
                 "license": package["license"], "repository": package["repository"],
                 "license_text_sha256": hashes}
        if package["license"] == "MPL-2.0":
            filename = f"{package['name']}-{package['version']}-source.tar.gz"
            source = source_archive(Path(package["manifest_path"]).parent,
                                    f"{package['name']}-{package['version']}")
            outputs[ASSETS / filename] = source
            entry["bundled_source"] = filename
            entry["source_sha256"] = sha(source)
        inventory.append(entry)
    header = [
        "Backgammon Buddy native Rust dependency notices",
        "Generated by tool/generate_native_notices.py from the locked Cargo graph.",
        "Includes normal and build dependencies for Windows GNU, Android ARM/ARM64 and iOS ARM64.",
        "Unused target/development-only dependencies are excluded. License alternatives are preserved.",
        "Direct wildbg engine licenses and model CC0 terms are provided separately.",
        "",
        "MPL source availability: dyn-eq 0.1.3 is unmodified. Complete source is",
        "included in assets/licenses/dyn-eq-0.1.3-source.tar.gz and is also available at",
        "https://crates.io/api/v1/crates/dyn-eq/0.1.3/download",
        "The same archive is distributed with this app's source repository.",
        "",
        "COMPONENTS",
    ]
    header.extend(f"{p['name']} {p['version']} — {p['license']} — {p['repository'] or ''}"
                  for p in inventory)
    for group in sorted(groups.values(), key=lambda g: g["components"][0]):
        header.extend(["", "=" * 72, *group["components"], "=" * 72, group["text"]])
    notices = ("\n".join(header).rstrip() + "\n").encode("utf-8")
    outputs[ASSETS / "native-dependencies.txt"] = notices
    record = {"cargo_lock_sha256": sha((ROOT / "native/engine_shim/Cargo.lock").read_bytes().replace(b"\r\n", b"\n")),
              "targets": TARGETS, "notice_sha256": sha(notices), "packages": inventory}
    outputs[ROOT / "native/licenses/inventory.json"] = (
        json.dumps(record, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    return outputs, len(packages), len(groups)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs, count, texts = generate()
    stale = []
    for path, data in outputs.items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    if stale:
        raise SystemExit("Stale native notices: " + ", ".join(stale))
    print(f"Native notices: {count} locked components, {texts} distinct license texts; "
          f"{'verified' if args.check else 'generated'} {len(outputs)} artifacts")


if __name__ == "__main__":
    main()
